In [5]:
import numpy as np

# 2. np.array([1,2,3]) 的 shape 属性返回？
arr = np.array([1, 2, 3])
print(arr.shape)

(3,)


In [9]:
# 3. np.array([[1,2],[3,4]]) 的 ndim 是？
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)

2


In [12]:
# 4. 向量 v=[1,2,3]，w=[4,5,6]，v+w 等于？
v = [1, 2, 3]
w = [4, 5, 6]
print(v + w)

v1 = np.array([1, 2, 3])
w1 = np.array([4, 5, 6])
print(v1 + w1)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [15]:
# 5. 向量 v=[1,2,3]，w=[4,5,6]，v·w（点积）等于？

v = [1, 2, 3]
w = [4, 5, 6]
print('v.w的点积:', np.array(v) * np.array(w))

v.w的点积: [ 4 10 18]


In [19]:
# 6 . np.dot(v,w) 和 v*w 的区别是？
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
print(np.dot(v, w))
print(v * w)
print(v @ w)

32
[ 4 10 18]
32


In [21]:
# 7. 向量 v=[3,4] 的范数（长度）|v| 是？
v = np.array([3, 4])
print(np.linalg.norm(v))

5.0


(m x p )@(n x p) = (m xp )

In [26]:
# 11. 矩阵 A 是 2×3，矩阵 B 是 3×4，A@B 的形状是？
v = np.random.rand(2, 3)

w = np.random.rand(3, 4)

print(v @ w)
print((v @ w).shape)


[[0.31764705 0.10875767 0.19240695 0.1410915 ]
 [1.17858105 0.53290548 1.16648456 0.8709664 ]]
(2, 4)


In [27]:
# 13. A=[[1,2],[3,4]]，B=[[5,6],[7,8]]，A@B 的左上角元素是？
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)

[[19 22]
 [43 50]]


In [28]:
# 14. 矩阵乘法满足交换律吗？即 A@B == B@A？
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)
print(B @ A)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [30]:
# 15. 矩阵 A=[[1,0],[0,1]]（单位矩阵）作用于向量 v 的效果是？import numpy as np

A = np.array([
    [1, 0],
    [0, 1]
])

v = np.array([3, 4])

print(A @ v)

[3 4]


In [32]:
# 20. np.arange(10) 生成什么？
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [33]:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
A = np.array([
    [1, 0],
    [0, 1]
])
print(A.T)

[[1 0]
 [0 1]]


In [36]:
# 27. 矩阵 [[2,0],[0,2]] 作用于向量的效果是？

A = np.array([[1,1],[1,2]])
B = np.array([[2,0],[0,2]] )
print(A @ B)

[[2 2]
 [2 4]]
